### ISSUE TITLE
[question] Performance vs memoizee

### ISSUE THREAD

**Issue by nealoke** [thinkloop/memoizerific#6]
Hi! I was really impressed by the benchmarks provided! But I was wondering what the difference between this and [memoizee](https://github.com/medikoo/memoizee) would be. Possible to test this as well?

**Comment by thinkloop** [comment]
Hello!

Memoizee was the main comparison in the benchmarks :-D

> Memoizee came in a solid second place, around 31% less performant than Memoizerific. In most scenarios this will not be very noticeable, in others, like memoizing in a loop, or recursively, it might be. Importantly though, it degraded gracefully, and remained within sub 1s levels almost all the time. Memoizee is acceptable for production use.

It's a good lib in general.

Also these tests were almost a year ago, it's possible today's version is faster or slower.

**Comment by nealoke** [comment]
@thinkloop OMG I'm not sure how I missed that o.O, Jesus I need to get some rest XD.

One burning question for me is then, how come you have such low stars in comparison to memoizee?

**Comment by nealoke** [comment]
@thinkloop Also do you have a way to invalidate the memoized result?

**Comment by thinkloop** [comment]
There are a lot of factors for stars. Memoizee has been around for 4+ years, memoizerific for just under a year. There's also a network effect, stars beget stars. The author could possibly famous in some circles, or has a large public presence tweeting a lot. Maybe memoizee is better in some use-cases - it does have more options available to configure. Those are some things I could think of. 

In the end memoizee is a good lib, and the differences in the vast majority of cases are probably negligible. 

The innovation with memoizerific is using the new Map object to store complex arguments (when available) so as to avoid expensive serialization, or lookups. My use-cases are heavily dependent on complex args. 

Using either lib wouldn't be a mistake. Both have been used in serious and heavy production scenarios.

**Comment by thinkloop** [comment]
>@thinkloop Also do you have a way to invalidate the memoized result?

The most straightforward way is to simply re-init the memoized fn:

```
let myExpensiveFunctionMemoized = memoizerific(50)((arg1, arg2, arg3) => {});

if (isInvalidationNeeded) {
   myExpensiveFunctionMemoized = memoizerific(50)((arg1, arg2, arg3) => {});
}
```
