### ISSUE TITLE
Webpack build warning

### ISSUE THREAD

**Issue by romulof** [thinkloop/memoizerific#7]
```
WARNING in ./~/memoizerific/memoizerific.js
Critical dependencies:
1:485-492 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
```

Point your `package.json` `main` script to a non-minified script, and add a `browser` entry pointing to minified version. It's a non-standard entry, but quite well supported.

https://github.com/defunctzombie/package-browser-field-spec#alternate-main---basic
https://github.com/substack/node-browserify#browser-field

PS: This also happen with https://github.com/thinkloop/map-or-similar

**Comment by romulof** [comment]
For now I'm adding these aliases in my Webpack config to prevent those warnings:
```js
...
  resolve: {
    alias: {
      'memoizerific': 'memoizerific/src/memoizerific',
      'map-or-similar': 'map-or-similar/src/map-or-similar',
    },
  },
...
```

**Comment by thinkloop** [comment]
Thanks for reporting this. Other build tools didn't complain, but it makes more sense anyway since this lib can be used in node as well. I've updated it as suggested.

Let me know if you notice any problems.
